version: '2'
networks:
  kafka_network:
    name: tweet_network_kafka_docker
services:
  mongo:
    image: mongo
    container_name: mongo
    ports: 
      - '27017:27017'
    networks: 
      - kafka_network
  
  tweetapp-api:
    image: tweetapp-api
    container_name: tweetapp-api
    ports:
      - '5000:5000'
    networks: 
      - kafka_network
    links:
      - mongo
      
  tweetapp-frontend:
    image: tweetapp-frontend
    container_name: tweetapp-frontend
    ports:
      - '4200:4200'
    networks: 
      - kafka_network
    depends_on:
      - tweetapp-api       
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka_network
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - kafka_network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
      
